### ISSUE TITLE
Files versioned by error?

### ISSUE THREAD

**Issue by ribeiroevandro** [diego3g/rocketredis#12]
Looking at the project, I found some files that I believe are not right.

First strange file in the project is `yarn-error.log` and then the presence of `yarn.lock` and `package-lock.json`.

What is the correct package manager?

**Comment by ribeiroevandro** [comment]
I believe it is time to define a contribution guide, what do you think?

**Comment by ruisaraiva19** [comment]
@ribeiroevandro both `yarn-error.log` and `package-lock.json` are being removed on #9.

**Comment by diego3g** [comment]
@ribeiroevandro We could use the same contribution guidelines from other open-source project: https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md

**Comment by diego3g** [comment]
Fixed :purple_heart:
