### ISSUE TITLE
Error when running the project

### ISSUE THREAD

**Issue by ribeiroevandro** [diego3g/rocketredis#13]
After cloning the project and installing all dependencies, both `yarn dev` commands that should be unique to execute the project or `yarn dev:react`and `yarn dev:electron` that would run each environment individually, don't work on MacOS. The Electron application is instantiated , but the application interface isn't open. Is there a step missing that is not clear? I looked at the video on YouTube, where the project was demonstrated to see the steps and I found no differences.

**Comment by Muurilo** [comment]
Here it is too, I tried to run "yarn dev" and also "yarn dev: react" "yarn dev: electron"

**Comment by AlefeChorna** [comment]
I had the same problem, tried to clear the cache among other things and it didn't run. Then, the only solution i got was to remove the repository and clone it again, this way it worked.

**Comment by diego3g** [comment]
Did you guys managed to solve the problem? Can you try to download the latest version and run again?

**Comment by diego3g** [comment]
Closing for now since there were no updates.
