### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by Muurilo** [diego3g/rocketredis#19]
It would be great and necessary to have support for multiple languages

**Comment by leoferreiralima** [comment]
I was thinking the same, you know some library to do this?

**Comment by Muurilo** [comment]
I'm already working on this feature, I'm using i18next but I'm having trouble running the project

**Comment by leoferreiralima** [comment]
If the problem keep please open a issue, my project in running, i am using the node12 and yarn 1.22.4 on ubuntu

**Comment by diego3g** [comment]
I think this is not an extremely necessary feature for the MVP but it's really cool that you working on it. If you're still developing this will be great if you create a new issue including the details of it following the example i did here (https://github.com/diego3g/rocketredis/issues/36).

I'll close the issue for now just to keep track only the stuff is really being implemented so i'll wait for your issue :purple_heart:
