### ISSUE TITLE
Build Commands

### ISSUE THREAD

**Issue by Muurilo** [diego3g/rocketredis#23]
Commands to build the app to windows, mac, linux

**Comment by diego3g** [comment]
I've used electron-builder a long time ago, can someone test it?

**Comment by ruisaraiva19** [comment]
I can take a shot at this GitHub [Electron Builder Action](https://github.com/samuelmeuli/action-electron-builder) 😉.

**Comment by diego3g** [comment]
Let's move this conversation to #38. Thanks! :heart:
