### ISSUE TITLE
README-to have more details about the repository

### ISSUE THREAD

**Issue by adarshsaraogi** [diego3g/rocketredis#27]
we could add some more brief details about the repository in which it could be included in the README File.

**Comment by adarshsaraogi** [comment]
@diego3g  what do you think and any suggestion?

**Comment by diego3g** [comment]
@adarshsaraogi i'm working on creating a project with all the tasks that should be done and the layout. Probably will do that until tomorrow night.

**Comment by diego3g** [comment]
I started designing the Rocket Redis UI inside Figma today (https://www.figma.com/file/YRor24p0TmTxcjl5L86jGb/Rocket-Redis?node-id=0%3A1), i'll try to get it done until tomorrow. Today i'll also create the project here inside Github with every task.

**Comment by diego3g** [comment]
I've created the project with the main functionalities i can think now for the application MVP.

Project: https://github.com/diego3g/rocketredis/projects/1

If you find anything that i could include there, feel free to open an issue and point me to add it to the project if we believe that it can be included in this first version.
