### ISSUE TITLE
Travis implementation for automation test & build.

### ISSUE THREAD

**Issue by adarshsaraogi** [diego3g/rocketredis#28]
we could also have the automation build & test pipeline for this repository using Travis CI and CD.

**Comment by ruisaraiva19** [comment]
Duplicated of #23

**Comment by diego3g** [comment]
I prefer using Github Actions as we don't need to maintain another tool.

**Comment by diego3g** [comment]
Closing since i'll create an issue with the details of what should be implemented about this. Thanks a lot!
