### ISSUE TITLE
Can not save connection

### ISSUE THREAD

**Issue by NguyenAnhDuc** [diego3g/rocketredis#30]
After test connection successfully, I can not save the connection. Nothing happen when I click save button!

Windows 10
Node 12

**Comment by JeremyLG** [comment]
Same here
Mac OSX Catalina 10.15.4
Node 14.4

**Comment by AlefeChorna** [comment]
The option **create connection** doesn't implemented yet

**Comment by profuel** [comment]
Same Fedora 31.

**Comment by diego3g** [comment]
The project is under development, we'll be implementing the core functionalities in the next days.

**Comment by profuel** [comment]
You've been advertised by https://twitter.com/tldrdan, so thus we're here and commenting....

**Comment by diego3g** [comment]
@profuel Cool! Thanks and welcome! We're building the project from zero so it's really early stage.
