### ISSUE TITLE
Connection list

### ISSUE THREAD

**Issue by diego3g** [diego3g/rocketredis#35]
It should be able to connect to a save connection to see its details like how many keys are stored inside of each included databases.

The user may connect just by double clicking the connection inside the connection list on the sidebar.

After that, a loading indicator should be shown during the connection process and after all that the user will get a visual feedback about the connection status.

**Red background:** Connection failed
**Purple background:** Connection successful

If the connection fails, the user can retry it clicking a button, otherwise, the user can see all of the databases inside the connection and how many keys there are inside of each one.

**Layout:** https://www.figma.com/file/YRor24p0TmTxcjl5L86jGb/Rocket-Redis?node-id=1%3A2

**Comment by natanaelsirqueira** [comment]
Hi @diego3g. Nice work so far!

I presume this is blocked by #34, but I already gave it a try and started to prepare the layout for this feature.

In the meantime, I could submit a PR just to add support for importing the .svg for the connection icon. What do you think?

**Comment by diego3g** [comment]
@natanaelsirqueira That's great to hear! I forgot to mention but i also started creating the connection list component and it's almost done. 

I'll send a PR right now so you can review if there is something i forgot or that you done better, alright?

**Comment by natanaelsirqueira** [comment]
@diego3g No problem at all! I learned something new today, that's what matters. :smile:
