### ISSUE TITLE
Add connection actions (edit, delete, etc...)

### ISSUE THREAD

**Issue by diego3g** [diego3g/rocketredis#37]
It should be able to execute some common operation with saved connections.

- Connect/disconnect;
- Edit settings;
- Refresh;
- Delete connection;

If not connected, the connect option will be available, otherwise the disconnect option will be visible.

The edit button must open the same modal used to create a connection but with the fields filled saving the connection in the end.

The refresh must be visible only after connected, this option refreshes all databases inside the connection and each individual key count.

The delete connection will delete permanently the connection from the store, it would be great to confirm with the user before the final delete, something like writing the name of the connection to delete or writing `DELETE`.

All of these options should be available when the user clicks with the right mouse button in a connection.

**Layout:** https://www.figma.com/file/YRor24p0TmTxcjl5L86jGb/Rocket-Redis?node-id=15%3A13

**Comment by natanaelsirqueira** [comment]
@diego3g I will work on this one, if that's okay.

**Comment by diego3g** [comment]
@natanaelsirqueira That's great!

**Comment by natanaelsirqueira** [comment]
@diego3g Do you have any recommendations for implementing the context menu? A library perhaps? I looked into a few options but can't decide which one is the right call.

**Comment by diego3g** [comment]
@natanaelsirqueira I don't remember to have something similar to share with you. Did you start to create something? I'm trying to get the MVP out this week so if you have something so we could work together to finish this.

**Comment by natanaelsirqueira** [comment]
@diego3g I opened a PR with only the layout because I wasn't sure about some things. I'm already working on the rest of the implementation while I wait for your feedback.
