### ISSUE TITLE
UI bug identified on Windows 10

### ISSUE THREAD

**Issue by felipeleite11** [diego3g/rocketredis#6]
Diego, I identified unexpected behavior in the top bar on Windows 10.

![Captura de Tela (299)](https://user-images.githubusercontent.com/54327441/86387796-19956d80-bc6a-11ea-9892-ef0066ba133e.png)

The configuration applied in the **electron/main.ts** file had no effect on Windows.

**Comment by diego3g** [comment]
Can you try passing `titleBarStyle: 'hidden'`? https://stackoverflow.com/a/48877027

**Comment by leonardolopesinf** [comment]
I also used windows 10 and didn't have this problem, it must be some option of the computer or version of windows...

**Comment by lenivene** [comment]
More bugs! The application open, but, don't work.
**Example:**
![e799481e76b68e31d00ccb6f53c0e33a](https://user-images.githubusercontent.com/9782458/86617675-fc281280-bf8d-11ea-91bd-edd66af4201a.gif)

**Comment by diego3g** [comment]
I'll try to execute this inside Windows to find out, but it seems to be something that happens only to some users :thinking:

**Comment by Muurilo** [comment]
This happened to me, but it was a problem in the project, after the boot command was updated my problem fixed

**Comment by filliperomero** [comment]
@felipeleite11 and @lenivene, you guys could provide more information, otherwise we can't help fix it (try at least).
Example:
- What is the SO? What is the SO version (not only windows 10 but the full version)
- Steps to reproduce that.
And other information

**Comment by filliperomero** [comment]
Just tried on 3 different machines with windows 10 and I couldn't reproduce the problem. If you guys can provide more informations, I can try to fix.

Steps I did:
- Clone the repository
- yarn -> To install dependencies
- yarn dev -> To run the program

**Comment by lenivene** [comment]
Let's go try again!
It's "working" now, but save don't work 😅
![039aff6f71874ccd060a2ae409114d14](https://user-images.githubusercontent.com/9782458/87111624-2d2f6e00-c240-11ea-8032-8f0c263f9ba3.gif)

**Comment by diego3g** [comment]
@lenivene I'm still working on "save": #34
