### ISSUE TITLE
UI: New Fonts

### ISSUE THREAD

**Issue by adarshsaraogi** [diego3g/rocketredis#86]
@diego3g can we come up with some new font style for this app. if yes let me know so i can work on this.

**Comment by filliperomero** [comment]
@adarshsaraogi which fonts are you thinking of?

**Comment by adarshsaraogi** [comment]
@filliperomero I have came up with these font type.

- Geometria Font Family   https://www.cufonfonts.com/font/geometria
- Galano Grotesque         https://www.fonts.com/font/rene-bieder/galano-grotesque
- Gilroy                             https://www.dafontfree.io/gilroy-font-family/
- Airbnb Cereal               https://airbnb.design/cereal/
- Cera Pro Font                 https://fontsfree.pro/base-web-fonts/sans-serif-grotesque/915-cera-pro.html
