### ISSUE TITLE
Error execute yarn dev

### ISSUE THREAD

**Issue by saymondamasio** [diego3g/rocketredis#97]
**Error when executing yarn dev**

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1595973395396-0.20066777516086587/node but npm is using /home/saymon/.nvm/versions/node/v12.17.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

System:
Windows 10 Pro with **WSL 2**

**Comment by saymondamasio** [comment]
It would be because I'm using nvm??

**Comment by diego3g** [comment]
I think the problem is that you installed Yarn with Node together, but i can't be 100% sure.

**Comment by saymondamasio** [comment]
I'll try with npm

**Comment by saymondamasio** [comment]
I think that developing Electron using wsl will not work because it does not render apps for now.

**Comment by ggmorais** [comment]
@saymondamasio In fact wsl can render GUI applications, like Electron, just follow these simple steps here https://www.scivision.dev/x11-gui-windows-subsystem-for-linux/  (I use Xming server and works perfect)

**Comment by saymondamasio** [comment]
@ggmorais Thanks, II'I try

**Comment by saymondamasio** [comment]
@ggmorais  
Just one more question, you develop react native in wsl using the server Xming?
It is possible?🤔

**Comment by ggmorais** [comment]
@saymondamasio I never tested but I think it is possible. If you run an Android/IOS emulator on wsl2 the Xming should render the gui normally, but I'm not sure, cause it would be a virtual machine running on a virtual machine 🤔. Otherwise if you're going to use the adb tools and a physical smartphone it would be a way more easier.
